### ISSUE TITLE
Question about model architecture.

### ISSUE THREAD

**Issue by benearnthof** [CompVis/fm-boosting#3]
Hello and thank you for this really interesting paper! 
I've tried to implement the paper and published a minimal example here: [https://github.com/benearnthof/fm_boosting/tree/main](https://github.com/benearnthof/fm_boosting/tree/main) but I'm not sure if the code works quite yet. The loss seems to be decreasing slowly, but I can only run it on a batch size of 8 so I don't have results quite yet 😅

My main question is about the noise concatenation step depicted in Figure 3 of the paper. 
If I understand correctly, we naively upsample the low resolution latents (with bilinear upsampling for example) and then concatenate noise to them so the tensors have the shapes:  
```python
(b, 4, 32, 32) -> (b, 4, 128, 128) -> (b, 8, 128, 128)  
```
The high resolution latents we get from the stable diffusion 1.5 KL Autoencoder have shape:
```python
(b, 4, 128, 128)
```
Which is also depicted in Figure 3 of your paper and consistent with the code in my script.   

My problem is here that, as far as I understand Flow Matching, the tensors from the source and target distribution must have the same shape, so how would that work with concatenating noise along any of the dimensions?   

In my script I fixed this by simply adding noise to the source tensor but I'm not sure if that is right. The TorchCFM implementation of OT-CFM also requires the source and target tensors to have the same shapes so I'm a bit confused.  

I hope I could outline my problem, and you'll be able to help me understand my mistake. Thanks again for the nice paper!

**Comment by stefan-baumann** [comment]
You should interpret the concatenated input as two underlying inputs: one is the "noisy" input for the flow matching process, the other is the conditioning signal. In this case, they just happen to be fed to the model concatenated into one tensor at the input.

**Comment by benearnthof** [comment]
Thanks for the quick reply! If I understand correctly, the main difference would then be in the UNet architecture. Where I simply add the noise to have the Input of the Unet be of shape 
```python
(b, 4, 128, 128)
```
Your Unet takes the concatenated input as is and then outputs tensors of the same dimension (?). I do think your approach makes more sense as it directly mixes in the noise instead of adding, but if the UNet is of sufficient capacity this should not make too much of a difference.  
Hope I interpreted your answer correctly, it seems that my implementation works but it will probably take another 2-3 days until I can sample from it.

**Comment by stefan-baumann** [comment]
Our U-Net takes inputs with 8 channels and produces outputs with 4. I think the current version of the paper might be a tiny bit confusing there, as we incorporate noise two times:
1) We add a bit of Gaussian noise to the upscaled latents (3.2.3 Noise Augmentation in the current preprint)
2) We concatenate a pure Gaussian noise vector to the input of the U-Net
Both are needed for good results from what we've seen. If I understood your description correctly, you're effectively only doing the first. That, however, still ends up effectively primarily training a model more akin to a regression model (that maps from noisy upscaled latent to clean latent) rather than an implicitly generative model that derives the stochasticity from the noise input similarly to how GANs work.
